---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm64

steps:
  - name: lint
    image: golangci/golangci-lint
    pull: if-not-exists
    commands:
      - golangci-lint run
  - name: test
    image: golang:1.18
    pull: if-not-exists
    commands:
      - go test ./... -v
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_PASSWORD: pa55Word!
      POSTGRES_USER: demo
      POSTGRES_DB: demodb
  - name: Build Binaries
    image: goreleaser/goreleaser
    pull: if-not-exists
    environment:
      CGO_ENABLED: "0"
    commands:
      - goreleaser build --snapshot --rm-dist --debug
  - name: Publish Dev
    image: plugins/docker
    pull: if-not-exists
    settings:
      insecure: true
      auto_tag: true
      auto_tag_suffix: linux-arm64
      dockerfile: docker/Dockerfile.linux.arm64
      registry: "localhost:5001/example/go-fruits-api"

services:
  - name: postgres
    image: postgres:14.4-alpine
    environment:
      POSTGRES_PORT: 5432
      POSTGRES_PASSWORD: pa55Word!
      POSTGRES_USER: demo
      POSTGRES_DB: demodb