apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: fruits-app-fruits-api-8080
  namespace: my-gloo
spec:
  kube:
    selector:
      app: cmd
      version: v1.0
    serviceName: cmd
    serviceNamespace: fruits-app
    servicePort: 8080