namespace: fruits-app
commonLabels:
  app: fruits-api
  version: v1.0
secretGenerator:
  - name: pgsql-credentials
    literals:
      - username=demo
      - password=pa55Word!
      - database=demodb
      - hostname=postgresql.db.svc.cluster.local
      - port=5432
configMapGenerator:
  - name: fruits-api-config
    files:
      - data.yaml
resources:
  - namespace.yaml
  - pvc.yaml
  - rbac.yaml
  - deployment.yaml
  - service.yaml
 